// Infynix Agency, India: depth content for the marketing service pages.
//
// Written for the Kerala market from the Kochi office: Malayalam and English,
// WhatsApp as the conversion path, the DPDP Act, NMC, ASCI and K-RERA rules,
// the Onam calendar, the Gulf diaspora, and the district-by-district shape of
// the state. Keyed by service slug, merged in index.js.

export const agencyDepth = {
  'infynix-agency': {
    overview: [
      'Infynix Agency is the marketing division of Infynix Solutions in India, working from Oberon Mall in Edappally. Search, paid social, YouTube, LinkedIn, local search, content, CRM automation and the measurement that ties them together, for businesses across Kerala and for Kerala brands selling to India and the Gulf. The division exists to make every rupee of marketing spend answerable to a number the accountant recognises.',
      'The Kerala market punishes marketing that is not measured. Click costs in healthcare, real estate, education and jewellery have risen steadily as national brands and local agencies bid for the same auctions, and a campaign that cannot tell a real enquiry from a junk form fill is simply feeding Google. So the plumbing goes in before the spend: tracking to the DPDP Act, CRM fields for source and campaign, WhatsApp and call tracking, offline conversions back to the platforms, and a written definition of a qualified enquiry that the sales team applies.',
      'Then the channels run, in Malayalam and English, structured by district because Kerala is fourteen markets, with creative produced by Infynix Media and landing pages and systems built by Infynix Growth Solutions. One brief, one team, one dashboard.',
      'Hospitals and clinics, developers, jewellery and retail chains, schools and colleges, resorts and restaurants, professional firms, NBFCs and Infopark companies selling beyond Kerala.',
    ],
    capabilitiesHeading: 'What the agency runs',
    capabilities: [
      { name: 'Performance advertising and paid media', desc: 'Google, Meta, YouTube and LinkedIn campaigns measured from spend to revenue, with offline conversions sent back to the platforms.' },
      { name: 'SEO and content marketing', desc: 'Technical remediation, Malayalam and English content and authority building, reported on organic enquiries rather than positions.' },
      { name: 'Local search and Google Business Profile', desc: 'Profiles, citations and reviews across every real branch, in both languages.' },
      { name: 'Social media management', desc: 'Bilingual calendars, monthly shoot days, community management and paid social run as performance.' },
      { name: 'Marketing automation and CRM', desc: 'Zoho, HubSpot and WhatsApp Business API flows so enquiries are answered and nurtured, with consent handled.' },
      { name: 'Analytics and attribution', desc: 'GA4, server-side tagging, call and WhatsApp tracking and one dashboard that reconciles to the accounts.' },
      { name: 'Diaspora campaigns', desc: 'Gulf, UK and US campaigns for brands whose buyers include NRI families, with a working view from our UAE and UK offices.' },
      { name: 'Creative from Infynix Media', desc: 'Video, photography and motion produced in Kerala for the campaigns, in both languages.' },
    ],
    specsHeading: 'Channels and what to expect',
    specsColumns: ['Channel', 'Time to first signal', 'Primary measure'],
    specs: [
      ['Google Search', '1 to 2 weeks', 'Cost per qualified enquiry'],
      ['Meta, Instagram and YouTube', '2 to 3 weeks', 'Cost per lead or order, quality from CRM'],
      ['LinkedIn (B2B)', '4 to 6 weeks', 'Meetings booked, pipeline value'],
      ['Diaspora campaigns', '3 to 4 weeks', 'Cost per WhatsApp conversation'],
      ['Local SEO', '8 to 12 weeks', 'Map pack visibility, calls, WhatsApp'],
      ['Organic search', '4 to 9 months', 'Organic enquiries by page'],
    ],
    useCasesHeading: 'Who the agency works with',
    useCases: [
      { name: 'Hospitals and clinics', desc: 'Groups and practices competing for high-value treatments within NMC and ASCI rules, from patients in Kerala and the Gulf.' },
      { name: 'Real estate', desc: 'Developers generating site visits from Kochi families and NRI buyers, with K-RERA compliance on every ad.' },
      { name: 'Jewellery and retail chains', desc: 'Multi-branch brands whose year is shaped by Onam, Vishu and wedding season.' },
      { name: 'Education', desc: 'Schools, colleges and coaching institutes with admissions cycles to plan around.' },
      { name: 'Hospitality and tourism', desc: 'Resorts and restaurants where Maps, Instagram and direct bookings are the goal.' },
      { name: 'Infopark and B2B', desc: 'SaaS and services companies selling from Kerala to India and abroad, measured on pipeline.' },
    ],
    engagementsHeading: 'How we work together',
    engagements: [
      { name: 'Growth retainer', desc: 'Strategy, channels, creative, automation and reporting on a monthly retainer, with budgets moved to what is producing.' },
      { name: 'Foundations project', desc: 'Tracking, consent, CRM, Business Profile and landing pages built before any spend.' },
      { name: 'Channel management', desc: 'One or two channels run inside a wider in-house team.' },
      { name: 'Audit and rescue', desc: 'A paid audit of accounts spending without producing, with a written plan.' },
    ],
    detail: [
      {
        heading: 'The definition of a lead is the whole argument',
        body: [
          'Most disagreements between a business and its agency come down to one undefined word. The agency counts a form fill as a lead. The sales team counts a person who picked up the phone and had the budget. The owner counts a sale. When the word is defined in writing in the first workshop and applied in the CRM by whoever handles enquiries, the argument ends and the campaigns can be judged on something real. Qualified enquiries and closed sales go back to Google and Meta as offline conversions, so the platforms optimise for what the business actually wants rather than for whoever fills forms fastest.',
          'Every report we send uses that definition, and the weekly note says what changed and what it produced against it.',
        ],
        points: [
          { name: 'Written definition', desc: 'Agreed in the first workshop, applied in the CRM.' },
          { name: 'Offline conversions', desc: 'Qualified enquiries and sales sent back to the platforms.' },
          { name: 'WhatsApp and calls counted', desc: 'Tracked as conversions, because that is where Kerala enquires.' },
          { name: 'Weekly note', desc: 'What changed and what it produced, every week.' },
        ],
      },
      {
        heading: 'Fourteen districts, two languages, one diaspora',
        body: [
          'A campaign that treats Kerala as one audience wastes budget in every district. Malabar responds to different creative and different Malayalam than Ernakulam; Trivandrum is a government and Technopark town; Thrissur runs on its own calendar. Several million Malayalis in the Gulf buy hospitals, flats, school places and gold from home, searching at Gulf hours and converting on WhatsApp. We structure campaigns by district and language, write Malayalam natively, run diaspora campaigns with a working view from our UAE office, and report by district so the business can see where the return really comes from.',
          'Most state-wide brands discover that two or three districts carry most of the revenue and that the budget had been spread evenly across all fourteen.',
        ],
        points: [
          { name: 'District campaigns', desc: 'Separate budgets, creative and reporting where the data supports it.' },
          { name: 'Malayalam native', desc: 'Written in the register of the district, never translated.' },
          { name: 'Diaspora campaigns', desc: 'Gulf hours, WhatsApp routing, a view from the UAE office.' },
          { name: 'Report by district', desc: 'Enquiries and revenue where they actually come from.' },
        ],
      },
      {
        heading: 'Rules that decide whether an ad runs at all',
        body: [
          'A doctor advertising a treatment is bound by National Medical Commission rules. A developer’s ad must carry the K-RERA number. A gold loan company or a chit fund answers to RBI and state regulation. A coaching institute’s placement claim falls under ASCI. On top of all of that, Google and Meta apply restricted-category policies that suspend accounts without warning, and an account suspended in the fortnight before Onam is a loss no dashboard records. Every piece of creative passes a sector checklist before it reaches a platform, and restricted-category verification is handled before the campaign is built.',
          'It protects the brand as much as the account.',
        ],
        points: [
          { name: 'Healthcare', desc: 'NMC and ASCI applied to claims, imagery and language.' },
          { name: 'Real estate', desc: 'K-RERA numbers and disclaimers on every ad and page.' },
          { name: 'Finance and education', desc: 'RBI, state and ASCI rules applied before launch.' },
          { name: 'Platform verification', desc: 'Restricted-category requirements met up front.' },
        ],
      },
      {
        heading: 'Creative, pages and systems from the same building',
        body: [
          'A media buyer, a production house and a web developer who have never met produce a campaign designed without the creative, creative shot without the landing page, and a landing page built without the tracking. At Infynix the three divisions share a brief. The Onam film is shot in July because the media plan needed it in August; the landing page carries Malayalam properly because the same team built the site; the WhatsApp enquiry lands in a CRM with its campaign attached because the technology team built the integration. The report covers all of it in one set of numbers.',
          'It is the difference between a supplier and a growth partner, and it is why the company is built the way it is.',
        ],
        points: [
          { name: 'Creative by Infynix Media', desc: 'Shot in Kerala, in both languages, for the platform.' },
          { name: 'Pages by Growth Solutions', desc: 'Prerendered, bilingual, tracked from day one.' },
          { name: 'Systems that catch the lead', desc: 'CRM, WhatsApp and automation built by the same team.' },
          { name: 'One dashboard', desc: 'Spend to revenue, reported once.' },
        ],
      },
    ],
    extraFaqs: [
      { question: 'What makes the agency different from a media buyer?', answer: 'A media buyer runs the platforms. We define the lead with you, build the tracking, consent, CRM routing and landing pages first, produce the creative with Infynix Media, run the channels, and report from spend to revenue in the numbers your accountant uses, moving budget weekly to what is producing.' },
      { question: 'Do you run Malayalam campaigns?', answer: 'Yes. Malayalam campaigns, copy and pages are written natively and run as a separate track with separate reporting, because Malayalam search and social behaviour differ from English and usually outperform for consumer brands.' },
      { question: 'Can you reach Malayalis in the Gulf?', answer: 'Yes. For hospitals, developers, schools, jewellers and premium services selling to NRI families, campaigns run into the UAE, Saudi Arabia, Qatar and Oman at Gulf hours, routed to WhatsApp, with a working view of that audience from our UAE office.' },
      { question: 'Will campaigns connect to our CRM?', answer: 'Yes. Google, Meta and LinkedIn lead flows are wired into Zoho, HubSpot, Salesforce or a custom CRM with source and campaign attached, and the WhatsApp Business API is integrated where the sales process runs there.' },
      { question: 'Do you handle NMC, K-RERA and ASCI rules in ads?', answer: 'Yes. A sector checklist is applied to every piece of creative before launch, and platform restricted-category verification is handled before the campaign is built.' },
      { question: 'Do you guarantee results?', answer: 'No, and we would be wary of any agency that does. We commit to a measured system, transparent methodology, honest weekly reporting and telling you when something is not working.' },
      { question: 'Where are you based?', answer: 'Third floor, Oberon Mall, Padivattom, Edappally, Kochi 682024. We work in person across Kerala and over shared channels, and we do not claim offices in other cities that we do not hold.' },
      { question: 'Can you work with our in-house marketing team?', answer: 'Yes. We take one or more channels, or the measurement and automation layer, and report into your meetings and tools. Account ownership stays with you.' },
    ],
  },

  'performance-advertising': {
    overview: [
      'Performance advertising for Kerala businesses: Google, Meta, YouTube and LinkedIn campaigns run as one measured system from Kochi, with spend judged on what it produced after the click and budgets moved weekly to whatever is producing. In a market where a hospital, a developer and a jeweller are bidding against national brands and each other, that discipline is the difference between a marketing budget and a donation.',
      'Performance advertising has come to mean running ads, which is not what it means. It means spending money only where it can be shown to return, and moving it as soon as the numbers say so. That requires measurement the platforms do not give you by default: what happened after the click, whether the enquiry was real, whether it became revenue, and what it cost against margin after returns and cash-on-delivery failures.',
      'We install that measurement first, define a qualified enquiry with you, send the outcomes back to the platforms so they optimise for what you actually want, and report the whole chain from spend to revenue by channel, campaign and district. Creative is produced by Infynix Media in Malayalam and English and tested on a cadence, because the creative and the landing page move cost per enquiry more than any bidding setting.',
      'We run paid media for hospitals and clinics, real estate, jewellery and retail, education, hospitality, e-commerce and B2B companies across Kerala, and into the Gulf for brands that sell to the diaspora.',
    ],
    capabilitiesHeading: 'What performance means here',
    capabilities: [
      { name: 'Attribution before spend', desc: 'Tracking, CRM fields, WhatsApp and call tracking, consent and an enquiry definition installed before a rupee goes to a platform.' },
      { name: 'Google Ads and Performance Max', desc: 'Search, Performance Max, Shopping and YouTube with offline conversion import and search term hygiene.' },
      { name: 'Meta and Instagram', desc: 'Campaigns with the Conversions API, audiences built from the CRM, and vertical creative produced for the platform.' },
      { name: 'YouTube', desc: 'Skippable and Shorts campaigns for a state that watches YouTube in Malayalam more than almost any other channel.' },
      { name: 'LinkedIn for B2B', desc: 'Account-based campaigns measured on meetings and pipeline for Infopark and Technopark companies.' },
      { name: 'Bilingual campaign structure', desc: 'Malayalam and English campaigns separated, with native copy and pages, reported on their own economics.' },
      { name: 'Creative testing cadence', desc: 'New hooks, formats and offers every few weeks from Infynix Media, with losers cut before they burn budget.' },
      { name: 'Contribution reporting', desc: 'Revenue after returns, COD failures, fees and discounts against spend, by campaign and product, not platform ROAS.' },
    ],
    specsHeading: 'Channels, timelines and what we measure',
    specsColumns: ['Channel', 'Time to first signal', 'Primary measure'],
    specs: [
      ['Google Search', '1 to 2 weeks', 'Cost per qualified enquiry'],
      ['Performance Max and Shopping', '3 to 4 weeks', 'Contribution after returns, new customer rate'],
      ['Meta and Instagram', '2 to 3 weeks', 'Cost per lead or order, quality from CRM'],
      ['YouTube', '3 to 4 weeks', 'View-through enquiries, brand search lift'],
      ['LinkedIn (B2B)', '4 to 6 weeks', 'Meetings booked, pipeline created'],
      ['Diaspora campaigns', '3 to 4 weeks', 'Cost per WhatsApp conversation by country'],
    ],
    useCasesHeading: 'Who this is built for',
    useCases: [
      { name: 'Hospitals and clinics', desc: 'High-value treatments where enquiry quality matters more than volume and every ad clears NMC and ASCI rules.' },
      { name: 'Real estate', desc: 'Site-visit generation from Kerala families and NRI buyers with agent routing and K-RERA compliance.' },
      { name: 'Jewellery and retail', desc: 'Onam, Vishu and wedding season campaigns with showroom visits and orders as the measure.' },
      { name: 'Education', desc: 'Admissions campaigns timed to the cycle, measured on enrolments.' },
      { name: 'E-commerce and D2C', desc: 'Shopping, Performance Max and social commerce with COD returns and fees counted in the numbers.' },
      { name: 'B2B and SaaS', desc: 'Companies selling from Kerala to India and abroad, measured on pipeline.' },
    ],
    engagementsHeading: 'How we work together',
    engagements: [
      { name: 'Performance retainer', desc: 'Channels, creative, testing and reporting monthly, with budgets moved to what is producing.' },
      { name: 'Foundations project', desc: 'Tracking, consent, CRM and landing pages built before spend begins.' },
      { name: 'Audit and rescue', desc: 'A paid audit of accounts spending without producing, with a written plan.' },
    ],
    detail: [
      {
        heading: 'Contribution, not ROAS',
        body: [
          'Platform ROAS is the most flattering number in marketing. It counts revenue before returns, before payment fees, before delivery, before cash-on-delivery orders that were refused at the door and before the cost of the goods, and it credits the platform for sales that would have happened anyway. A Kerala D2C brand with a high COD rejection rate can show a healthy ROAS while losing money on every paid order.',
          'We report contribution: revenue after returns, fees, delivery, COD failures and discounts, against spend, by campaign and product. It is a less flattering number and it is the only one that tells the business whether to spend more.',
        ],
        points: [
          { name: 'Returns and COD counted', desc: 'Rejections and refunds reconciled against the campaigns that produced the orders.' },
          { name: 'Fees and delivery', desc: 'Gateway and courier costs deducted.' },
          { name: 'Incrementality', desc: 'Brand and existing-customer revenue separated from genuinely new demand.' },
          { name: 'Product-level view', desc: 'Contribution by product and category, so the feed is bid accordingly.' },
        ],
      },
      {
        heading: 'YouTube and Meta in Malayalam',
        body: [
          'Kerala watches YouTube in Malayalam at a rate few markets match, and Instagram is where retail, hospitality and real estate are discovered. Campaigns built in English for a desktop form-filler miss most of it. We structure by language and intent, write Malayalam ads and pages natively, and produce vertical creative for each platform with Infynix Media rather than cropping a landscape ad four ways.',
          'The Kerala calendar shapes the plan too: Onam prepared weeks ahead, Vishu and wedding season budgets timed to the buying windows, admissions campaigns live when parents start searching, and the monsoon shift to online planned rather than discovered.',
        ],
        points: [
          { name: 'Malayalam campaigns', desc: 'Separate campaigns, copy and pages, reported on their own numbers.' },
          { name: 'Platform-native creative', desc: 'Reels, Shorts and YouTube creative produced in Kerala.' },
          { name: 'Onam and seasons', desc: 'Planned into budgets and creative in advance.' },
          { name: 'WhatsApp conversions', desc: 'Click-to-WhatsApp tracked and routed, because that is where the enquiry happens.' },
        ],
      },
      {
        heading: 'Rules that apply to paid media in Kerala',
        body: [
          'Doctors and hospitals are bound by NMC restrictions on promotion. Real estate ads must carry the K-RERA number. Financial products have RBI rules, education claims fall under ASCI guidance, and Google and Meta add restricted-category policies that suspend accounts without warning. An account suspended in the week before Onam is a cost no report shows.',
          'We keep a checklist per sector, run creative through it before launch, and set accounts up with the verifications the platforms require for restricted categories.',
        ],
        points: [
          { name: 'Healthcare review', desc: 'Claims, imagery and language checked against NMC and ASCI guidance.' },
          { name: 'Real estate compliance', desc: 'K-RERA numbers and disclaimers on every ad and page.' },
          { name: 'Platform certification', desc: 'Restricted-category verification handled up front.' },
          { name: 'Education and finance', desc: 'Claims handled to ASCI and RBI rules before launch.' },
        ],
      },
      {
        heading: 'Creative and landing pages as the lever',
        body: [
          'Once measurement is in place, the biggest lever in a performance account is not the bid. It is the creative and the page. New hooks and formats move cost per enquiry more than any bidding setting, and a landing page test on the offer, the form or the proof moves it again. Most accounts we audit have not changed creative in months and have never tested the page.',
          'We run both on a cadence: new creative every few weeks in both languages, and structured page tests with the numbers deciding, with the winners applied to the pages that rank organically as well.',
        ],
        points: [
          { name: 'Creative cadence', desc: 'New hooks and formats on a schedule, produced by Infynix Media.' },
          { name: 'Page testing', desc: 'Headlines, offers, forms and proof tested structurally.' },
          { name: 'Losers cut early', desc: 'Underperforming creative and pages retired before they burn budget.' },
          { name: 'Winners scaled', desc: 'What works gets the budget, and feeds the organic pages.' },
        ],
      },
    ],
    extraFaqs: [
      { question: 'What is the difference between performance advertising and digital marketing?', answer: 'Performance advertising is the discipline of spending only where return can be shown and moving budget as the numbers dictate. It sits inside digital marketing alongside organic search, content, social and automation. This page covers paid media; the Infynix Agency page covers the wider programme.' },
      { question: 'How much should we spend to get a readable result?', answer: 'It depends on your category and the Kerala cost per click in it. We state the minimum before you commit, and we will say if the budget is too small to produce a signal rather than take it and report clicks.' },
      { question: 'Do you report on ROAS?', answer: 'We report contribution: revenue after returns, COD failures, fees, delivery and discounts, against spend, by campaign and product. Platform ROAS is shown for reference but decisions are not made on it.' },
      { question: 'Can you run campaigns into the Gulf?', answer: 'Yes. Diaspora campaigns are structured by country with Malayalam and English creative, timed to Gulf hours, routed to WhatsApp and reported on cost per conversation by country.' },
      { question: 'Do you guarantee a cost per lead?', answer: 'No. We set a target from your margin and close rate in the first workshop and report against it from month one, and we tell you honestly when it is not being met and why.' },
      { question: 'Do you handle NMC and K-RERA requirements in ads?', answer: 'Yes. Healthcare and real estate creative is checked against NMC, ASCI and K-RERA requirements before launch, and platform restricted-category verification is handled up front so accounts are not suspended mid-campaign.' },
      { question: 'Do you manage product feeds for Shopping?', answer: 'Yes. Feed optimisation, custom labels by margin and role, availability sync and supplemental data are part of every Shopping and social commerce engagement, because the feed is the campaign.' },
      { question: 'Can you work alongside our in-house team?', answer: 'Yes. We take one or more channels, or the measurement layer, and report into your existing tools. Accounts stay in your name.' },
      { question: 'Do you run YouTube campaigns in Malayalam?', answer: 'Yes. Kerala watches YouTube in Malayalam at a rate few markets match, and skippable and Shorts campaigns with Malayalam creative produced by Infynix Media are a core channel for consumer brands here.' },
      { question: 'How quickly can you start?', answer: 'Foundations begin within two weeks of agreement, and the first campaigns are typically live in the third or fourth week once the measurement can be trusted.' },
    ],
  },

  'seo-content-marketing': {
    overview: [
      'SEO and content marketing for Kerala businesses: content planned from what people in Kochi, Kozhikode, Thrissur and Trivandrum actually search, in Malayalam and English, written with your experts, structured so search engines and AI assistants can quote it, and supported by the technical foundation and the authority that let it rank. Reported on organic enquiries, not on rankings.',
      'Most content marketing in Kerala is a blog nobody planned, written by nobody in particular, about topics nobody searched for. It produces pages, not enquiries. Content that works starts from demand: the questions patients, parents, buyers and procurement teams type into Google, the answers they need, and the language they search in. Then it is written by someone who knows the answer, and it is built to be found.',
      'We run content as a programme alongside the technical and local SEO work: demand research in both languages, an editorial calendar, expert-led writing, Malayalam that is native rather than translated, structured data and internal linking, and monthly reporting on what each piece produced.',
      'We work with hospitals and clinics, schools and colleges, real estate developers, law and financial firms, tourism and hospitality, and B2B companies selling from Kerala to India and abroad.',
    ],
    capabilitiesHeading: 'What the programme delivers',
    capabilities: [
      { name: 'Demand research in two languages', desc: 'Keyword and question research in Malayalam, Manglish and English, mapped to the intents that produce enquiries.' },
      { name: 'Editorial calendar', desc: 'Service, guide, comparison and locality content planned quarterly from demand and the Kerala calendar.' },
      { name: 'Expert-led writing', desc: 'Written with your doctors, teachers, engineers or advisers so it is accurate and specific, not generic.' },
      { name: 'Native Malayalam content', desc: 'Written in Malayalam by native speakers, never translated, in the register the audience uses.' },
      { name: 'Quotable structure', desc: 'Clear headings, direct answers and FAQ markup so search engines and AI assistants can lift the answer.' },
      { name: 'Technical foundation', desc: 'Crawlability, rendering, Core Web Vitals and structured data fixed so the content can be found.' },
      { name: 'Authority building', desc: 'Links and mentions earned from Kerala and Indian publishers, associations and institutions. No bought links.' },
      { name: 'Reporting on enquiries', desc: 'Search Console, GA4 and CRM connected so each piece is reported on the enquiries it produced.' },
    ],
    specsHeading: 'What to expect and when',
    specsColumns: ['Workstream', 'Typical timeline', 'Evidence it is working'],
    specs: [
      ['Demand research and calendar', 'Weeks 1 to 3', 'A quarter of content planned from real demand'],
      ['Technical remediation', 'Weeks 1 to 6', 'Indexed pages up, errors down in Search Console'],
      ['Content production', 'Month 2 onwards', 'Impressions and clicks on new pages'],
      ['Malayalam track', 'Month 2 onwards', 'Malayalam impressions and enquiries'],
      ['Authority building', 'Month 3 onwards', 'Referring domains, page-level rankings'],
      ['Competitive terms', 'Months 6 to 12', 'Page one positions, enquiries by query'],
    ],
    useCasesHeading: 'Who this is for',
    useCases: [
      { name: 'Hospitals and clinics', desc: 'Condition, treatment and doctor content that patients search, within NMC rules, in both languages.' },
      { name: 'Education', desc: 'Course, admission, fee and campus content aligned to what parents and students search and when.' },
      { name: 'Real estate', desc: 'Locality guides, project pages and buyer content that compete with the portals.' },
      { name: 'Professional services', desc: 'Practice area and guide content that establishes expertise for careful clients.' },
      { name: 'Tourism and hospitality', desc: 'Destination and experience content that ranks alongside the OTAs and drives direct bookings.' },
      { name: 'B2B and SaaS', desc: 'Problem, comparison and capability content for buyers in India and abroad.' },
    ],
    engagementsHeading: 'How we engage',
    engagements: [
      { name: 'Content and SEO retainer', desc: 'The full programme monthly, with the balance of technical, content and authority work adjusted as the data dictates.' },
      { name: 'Content programme', desc: 'Bilingual content on a set cadence for businesses with the technical basics in place.' },
      { name: 'Content audit', desc: 'A review of what exists, what ranks, what to consolidate and what to write next.' },
    ],
    detail: [
      {
        heading: 'Malayalam search is the widest gap in Kerala',
        body: [
          'Malayalam and Manglish queries carry real demand across every consumer category in the state, and the quality of content answering them is poor. That gap is the single largest organic opportunity in Kerala. Translated English pages do not close it, because Malayalam readers recognise translation and Google treats it accordingly. Content written natively in Malayalam, by someone who knows the subject, ranks where nothing else does.',
          'We research Malayalam demand directly, write natively, mark up language versions correctly and report the Malayalam track on its own, so the business can see the return and invest in it.',
        ],
        points: [
          { name: 'Malayalam demand research', desc: 'Queries mapped from Malayalam and Manglish search data with spelling variants.' },
          { name: 'Native writing', desc: 'Content written in Malayalam by native speakers.' },
          { name: 'Language markup', desc: 'Versions served correctly to the right searcher.' },
          { name: 'Separate reporting', desc: 'Traffic, rankings and enquiries by language.' },
        ],
      },
      {
        heading: 'Content a careful reader can trust',
        body: [
          'Kerala buyers research. A parent choosing a school, a patient choosing a specialist, a family buying an apartment, a finance director shortlisting a supplier: each reads more than a consumer buying on impulse. Content has to be accurate, specific and credible, with the credentials, processes and evidence the reader is looking for, and it has to stay within the rules that apply to healthcare, education and financial claims.',
          'We plan content from what those readers search, write it with subject matter input from your team, and structure it with clear headings, direct answers and FAQ markup so search engines and AI assistants can quote it directly.',
        ],
        points: [
          { name: 'Demand-led planning', desc: 'Topics from search data and the questions your team actually gets.' },
          { name: 'Expert input', desc: 'Written with your clinicians, teachers or engineers.' },
          { name: 'Claims within rules', desc: 'NMC, ASCI and RBI expectations applied to every page.' },
          { name: 'Quotable structure', desc: 'Headings, direct answers and FAQ markup.' },
        ],
      },
      {
        heading: 'Competing with portals and national brands',
        body: [
          'For most Kerala commercial searches the first page is held by Practo, Justdial, Sulekha, the property portals, national ed-tech brands and aggregators, not by the businesses that do the work. They hold those positions with scale and authority, and they charge the businesses listed on them for the leads. The way past them is to give Google what they cannot: first-hand content about your services, your locality and your customers, a Business Profile that outperforms a listing, and reviews that read as real.',
          'We map which portals hold which terms, find the queries where a local page can win, and displace them one term at a time.',
        ],
        points: [
          { name: 'Portal mapping', desc: 'Which aggregators hold which terms, and where the gaps are.' },
          { name: 'First-hand content', desc: 'Pages that say what only the business doing the work can say.' },
          { name: 'Business Profile strength', desc: 'A profile that beats a listing for a local search.' },
          { name: 'Term by term', desc: 'Displacing portals on the queries that convert.' },
        ],
      },
      {
        heading: 'Content that feeds the rest of the marketing',
        body: [
          'A guide that ranks is also the email that nurtures, the script for a Reel, the answer the WhatsApp assistant gives and the proof the sales team sends. Content produced once and used everywhere is how a Kerala business with a small team publishes like a large one. We plan content with the agency and media teams so the guide, the video and the campaign come from one brief.',
          'The reporting shows what each piece produced across channels, not just in search.',
        ],
        points: [
          { name: 'One brief, many formats', desc: 'Guide, video, email and social from the same research.' },
          { name: 'Sales enablement', desc: 'Content the sales team can send to close.' },
          { name: 'Assistant knowledge', desc: 'Content that powers the answers on WhatsApp and the site.' },
          { name: 'Cross-channel reporting', desc: 'What each piece produced, wherever it ran.' },
        ],
      },
      {
        heading: 'Content for the Gulf diaspora',
        body: [
          'For hospitals, developers, schools and jewellers, some of the most valuable search demand comes from outside Kerala: a Malayali family in Dubai researching a hospital for a parent, an apartment for retirement, a school for a child returning home. They search in English and Malayalam, at Gulf hours, with questions a local page rarely answers: how to arrange a consultation from abroad, how payment works, what happens on the visit home.',
          'We plan diaspora content from that demand, answer the questions the local page misses, and structure it so it ranks for searches made in the UAE and the Gulf, with a working view of the audience from our UAE office.',
        ],
        points: [
          { name: 'Diaspora demand research', desc: 'What NRI families search, from where, in which language.' },
          { name: 'Questions the local page misses', desc: 'Arranging from abroad, payment, the visit home.' },
          { name: 'Gulf search targeting', desc: 'Content and markup that rank for searches made in the UAE.' },
          { name: 'WhatsApp conversion', desc: 'The enquiry path the diaspora actually uses.' },
        ],
      },
    ],
    extraFaqs: [
      { question: 'Do you write in Malayalam?', answer: 'Yes, natively, by native speakers, from Malayalam demand research, and reported as a separate track so you can see what each language produces. For most Kerala consumer categories the Malayalam track is where the fastest organic wins are.' },
      { question: 'Who writes the content?', answer: 'Our writers, with your subject matter experts involved rather than just approving, so the content is accurate and specific. Healthcare, education and financial content is checked against NMC, ASCI and RBI expectations before publication.' },
      { question: 'How long does content take to produce enquiries?', answer: 'New pages typically show impressions within weeks and enquiries within two to four months, with competitive terms taking six to twelve months of sustained work. Leading indicators are reported monthly.' },
      { question: 'Can a local business outrank Practo or the property portals?', answer: 'For specific local and service terms, yes. Portals win on scale, but a local business can win with first-hand content, a strong Business Profile and genuine reviews on the queries that actually convert.' },
      { question: 'Do you buy links?', answer: 'No. Authority is earned from Kerala and Indian publishers, associations and institutions through genuinely useful content and outreach.' },
      { question: 'Can you audit our existing content?', answer: 'Yes. A content audit reviews what exists, what ranks, what to consolidate, what to rewrite and what to write next, with the plan prioritised by demand.' },
      { question: 'Do you work with our developers for the technical side?', answer: 'Either way. We hand precise tickets to your team and verify the fixes, or the Infynix technology team makes the changes.' },
      { question: 'How do you report?', answer: 'Monthly with Search Console, GA4 and CRM connected, showing organic enquiries and revenue by page, query and language, with a short weekly note on what changed.' },
      { question: 'Can content reach Malayalis in the Gulf?', answer: 'Yes. Diaspora content is planned from what NRI families search, answers the questions a local page misses, and is structured to rank for searches made in the UAE and the Gulf, with WhatsApp as the conversion path.' },
    ],
  },

  'social-media-management': {
    overview: [
      'Social media management from Kochi for brands that need to publish every week in Malayalam and English without turning every post into a production. Instagram, YouTube, Facebook and LinkedIn, run on a monthly rhythm: a planning session, a shoot day with Infynix Media, editing for each platform, a calendar approved in one pass, community management every day, paid social run as performance, and a report that counts enquiries rather than likes.',
      'Malayalam social media is its own culture, with its own humour, its own creators and a comment section that rewards wit and punishes pretension. Content that works nationally often lands flat here, and content that works in Kochi may not travel to Malappuram. We write Malayalam first for consumer brands, adjust the register by district, and test rather than assume, because the numbers decide.',
      'Community management is treated as a sales channel, because in Kerala the enquiry arrives in the DM. A question about a necklace, a table, a treatment or a flat is a lead, and it is lost if it is answered on Monday. We answer same day, seven days a week, in the language the customer used, and route the enquiry to sales or the CRM with its source attached.',
      'Jewellery and textile chains, restaurants and resorts, hospitals and clinics, developers, schools and colleges, and professional firms across Kerala.',
    ],
    capabilitiesHeading: 'What management includes',
    capabilities: [
      { name: 'Bilingual content calendar', desc: 'Malayalam and English planned together each month, with themes, offers and the shoot list, in the register the audience uses.' },
      { name: 'Monthly shoot day', desc: 'Infynix Media produces 15 to 25 vertical clips and the stills the month needs, on location across Kerala.' },
      { name: 'Platform-native editing', desc: 'Reels, Shorts and YouTube cut for each platform, with open captions in both languages.' },
      { name: 'Community management', desc: 'Comments and DMs answered same day, seven days a week, in the language the customer wrote in, with enquiries routed to sales.' },
      { name: 'Paid social as performance', desc: 'Structured campaigns with the Conversions API, tracked WhatsApp enquiries and creative testing, not boosted posts.' },
      { name: 'Creator collaborations', desc: 'Kerala creators matched on audience fit, with deliverables and tracking agreed in writing.' },
      { name: 'Reputation and reviews', desc: 'Google, Practo, Zomato and the platforms your sector uses, managed as part of the same programme.' },
      { name: 'Monthly reporting', desc: 'Reach, saves, profile visits, enquiries and revenue, feeding the next planning session.' },
    ],
    specsHeading: 'Formats and cadence',
    specsColumns: ['Format', 'Typical cadence', 'What we measure'],
    specs: [
      ['Reels and Shorts', '12 to 20 per month', 'Reach, saves, profile visits, enquiries'],
      ['Static and carousel posts', '8 to 12 per month', 'Engagement, saves, link clicks'],
      ['Stories', 'Daily', 'Replies, sticker taps, WhatsApp clicks'],
      ['Paid social', 'Always on plus seasonal', 'Cost per enquiry or order, revenue'],
      ['Creator content', '1 to 4 per month', 'Reach, redemptions, enquiries'],
      ['Community management', 'Same day, 7 days', 'Response time, conversion of DMs'],
    ],
    useCasesHeading: 'Who this is for',
    useCases: [
      { name: 'Jewellery and textiles', desc: 'Showrooms whose Instagram is the window and whose year is shaped by Onam and wedding season.' },
      { name: 'Restaurants and resorts', desc: 'Venues where a Reel decides who books, and where reviews decide who returns.' },
      { name: 'Hospitals and clinics', desc: 'Doctor-led educational content that builds trust within NMC rules.' },
      { name: 'Real estate', desc: 'Developers building an audience of Kerala and NRI buyers with project and locality content.' },
      { name: 'Education', desc: 'Schools and institutes whose admissions depend on parents and students on Instagram and YouTube.' },
      { name: 'Professional and B2B', desc: 'Founder and expertise content on LinkedIn for firms whose reputation is the product.' },
    ],
    engagementsHeading: 'How we work together',
    engagements: [
      { name: 'Social retainer', desc: 'Calendar, shoot day, editing, community management and paid social monthly.' },
      { name: 'Production only', desc: 'Shoot days and editing for an in-house team that runs its own channels.' },
      { name: 'Paid social management', desc: 'Campaigns run as performance inside a wider marketing team.' },
    ],
    detail: [
      {
        heading: 'The rhythm is the product',
        body: [
          'Brands that publish consistently for a year build an audience that campaigns can then convert. Brands that post in bursts around a launch and go quiet start over every time. The rhythm is what we sell: a planning session each month that turns what the business needs to sell and what the audience is asking into twenty ideas, a shoot day that produces them, editing and captions in both languages, a calendar approved once rather than post by post, and a report that sets the next month.',
          'For multi-branch brands the shoot rotates across showrooms and cities so every district sees itself in the content.',
        ],
        points: [
          { name: 'Monthly planning', desc: 'Themes, offers, season and the shoot list agreed once.' },
          { name: 'One shoot day', desc: 'A month of Reels and stills produced by Infynix Media.' },
          { name: 'Approved in one pass', desc: 'A scheduled calendar reviewed once.' },
          { name: 'Branch rotation', desc: 'Content shot across locations for chains.' },
        ],
      },
      {
        heading: 'Onam, Vishu and the wedding season as content arcs',
        body: [
          'Every Kerala brand posts an Onam greeting on the day. The ones that win run Onam as a season: anticipation in July, offers and stories through the shopping weeks, the peak on Thiruvonam, and the days after. Vishu, the wedding season, school admissions and, for Malabar audiences, Ramadan and Eid each have their own arc. We plan the calendar around them months ahead, shoot seasonal content before it is needed, and pair it with paid campaigns timed to the buying windows.',
          'The monsoon, when footfall drops and attention moves online, is planned too, because it is when a well-run account gains the most ground.',
        ],
        points: [
          { name: 'Season arcs', desc: 'Planned from anticipation to peak to aftermath.' },
          { name: 'Shot ahead', desc: 'Seasonal content produced weeks before it runs.' },
          { name: 'Paid aligned', desc: 'The strongest clips promoted in the buying window.' },
          { name: 'Monsoon plan', desc: 'Content for the weeks when attention is online.' },
        ],
      },
      {
        heading: 'The DM is the enquiry',
        body: [
          'A comment asking the price, a message asking if a table is free on Saturday, a DM asking whether a doctor sees patients on Sundays: each is a lead in the language the customer chose, and it converts if answered within the hour and is lost by the next morning. Community management is staffed for that: same day, seven days a week, replies in Malayalam or English as the customer wrote, enquiries passed to the sales team or the CRM with their source attached, and the conversation moved to WhatsApp Business where the sale happens.',
          'Response time and DM conversion are in the monthly report, because that is what social is for.',
        ],
        points: [
          { name: 'Same day, every day', desc: 'Comments and DMs answered seven days a week.' },
          { name: 'In the customer’s language', desc: 'Malayalam or English as they wrote.' },
          { name: 'Routed to sales', desc: 'With source attached, into the CRM.' },
          { name: 'Measured', desc: 'Response time and DM conversion reported monthly.' },
        ],
      },
      {
        heading: 'Paid social that is measured, not boosted',
        body: [
          'Boosting a post produces likes. A structured campaign with objectives, audiences by district, creative tests, the Conversions API installed server-side and tracked WhatsApp enquiries produces enquiries at a cost the business can see. The strongest organic content becomes the paid creative, the paid data feeds the organic plan, and the whole thing is reported from spend to revenue by the agency team that runs it.',
          'Healthcare, education and financial content is checked against NMC, ASCI and RBI rules before it is promoted, because a viral post that breaches them is a liability rather than a win.',
        ],
        points: [
          { name: 'Structured campaigns', desc: 'Objectives, district audiences and creative tests.' },
          { name: 'Conversions API', desc: 'Server-side tracking so results survive privacy changes.' },
          { name: 'Creative from organic', desc: 'The best-performing posts promoted with budget.' },
          { name: 'Rules checked', desc: 'NMC, ASCI and RBI applied before promotion.' },
        ],
      },
    ],
    extraFaqs: [
      { question: 'Do you produce the content or only schedule it?', answer: 'We produce it. Infynix Media runs a monthly shoot day in Kochi or wherever the brand is, producing the Reels and stills the calendar needs, edited for each platform with captions in Malayalam and English, and the calendar is scheduled and managed from there.' },
      { question: 'Do you write in Malayalam?', answer: 'Yes, natively, by native speakers, with the register adjusted by district, and for most consumer brands Malayalam is written first because it outperforms.' },
      { question: 'Who answers comments and DMs?', answer: 'We do, same day, seven days a week, in the language the customer wrote in, with enquiries routed to your sales team or CRM and moved to WhatsApp Business where the sale happens.' },
      { question: 'Do you work with Malayalam creators?', answer: 'Yes. Creators are matched on audience fit rather than follower count, deliverables and tracking are agreed in writing, and each collaboration is reported on what it produced.' },
      { question: 'How is social media measured?', answer: 'Reach, saves and profile visits as leading indicators; enquiries, WhatsApp conversations and revenue as the measure, reported monthly and used to plan the next month.' },
      { question: 'Can you manage a chain with showrooms across Kerala?', answer: 'Yes. Shoot days rotate across locations so every district sees itself, paid campaigns are segmented by district and language, and the report shows enquiries by branch.' },
      { question: 'Can you run only the paid layer?', answer: 'Yes. Paid social is run as performance marketing inside a wider in-house or agency team, with the Conversions API, tracked enquiries and creative testing, reporting into your tools.' },
      { question: 'Can you handle a hospital or school account within the rules?', answer: 'Yes. A checklist per sector covering NMC, ASCI and platform policies is applied to every post before it is scheduled or promoted.' },
      { question: 'How quickly can you start?', answer: 'Planning can begin within two weeks of agreement, with the first shoot day and a scheduled calendar typically live inside the first month.' },
      { question: 'Do you manage reviews as well?', answer: 'Yes. Google, Practo, Zomato and the platforms your sector uses are managed within the same programme, with a steady, genuine review process and replies in the customer’s language.' },
    ],
  },

  'marketing-automation-crm': {
    overview: [
      'CRM and marketing automation from Kochi for businesses whose sales happen on WhatsApp and whose leads arrive at ten at night. The point is simple: a lead answered in two minutes converts, a lead answered the next morning has already spoken to three competitors, and no sales team can be awake all the time. Automation does the first two minutes and the follow-ups; the CRM makes sure every conversation is recorded, routed and measured; and the salesperson keeps working from the phone they already use.',
      'Most Kerala businesses have tried a CRM and abandoned it, because it expected the sales team to stop using WhatsApp and start filling forms at a desk. We do the opposite. The WhatsApp Business API goes inside the CRM: enquiries arrive there, conversations are logged against the customer automatically, templated replies go out instantly in Malayalam or English, and the salesperson replies from their phone as before. The CRM fills itself.',
      'Around that sit routing rules that send each lead to the right branch or person in seconds, nurture sequences that keep a long sales cycle warm without becoming noise, consent handled to the DPDP Act, and reporting that shows the pipeline from enquiry to closed sale by source, campaign and branch.',
      'Hospitals and clinic groups, developers, schools and colleges, jewellery and retail chains, NBFCs, professional firms and B2B companies across Kerala, and Kerala brands selling to the Gulf.',
    ],
    capabilitiesHeading: 'What we build',
    capabilities: [
      { name: 'CRM implementation', desc: 'Zoho, HubSpot, Salesforce or a custom CRM implemented for how your team actually sells, with pipelines, stages and fields that match the process.' },
      { name: 'WhatsApp Business API', desc: 'Enquiries, replies, notifications and templated follow-ups through the channel Kerala customers use, logged against the CRM record.' },
      { name: 'Lead capture and routing', desc: 'Web, WhatsApp, calls, ads, portal and walk-in leads captured with source and campaign, deduplicated and routed to the right person or branch within minutes.' },
      { name: 'Automated follow-up', desc: 'Sequences by WhatsApp, email and SMS that respond instantly, qualify and nurture in Malayalam or English, with a person stepping in at the right moment.' },
      { name: 'Lead scoring and qualification', desc: 'Simple scores applied from behaviour and CRM data so sales works the leads most likely to close.' },
      { name: 'Sales enablement', desc: 'Quotes, brochures, booking links and documents generated from the CRM, in both languages.' },
      { name: 'Consent and DPDP', desc: 'Marketing consent captured, recorded and honoured to the Digital Personal Data Protection Act.' },
      { name: 'Reporting and attribution', desc: 'Pipeline, conversion and revenue by source, campaign and branch, connected to the ad platforms for offline conversion import.' },
    ],
    specsHeading: 'Typical engagements and timelines',
    specsColumns: ['Engagement', 'Typical timeline'],
    specs: [
      ['CRM implementation for a sales team', '4 to 8 weeks'],
      ['WhatsApp Business API integration', '2 to 4 weeks'],
      ['Lead routing and automation build', '3 to 6 weeks'],
      ['Migration from spreadsheets or another CRM', '4 to 10 weeks'],
      ['Ongoing automation and optimisation', 'Monthly'],
    ],
    useCasesHeading: 'Who this is for',
    useCases: [
      { name: 'Hospitals and clinic groups', desc: 'Enquiry to consultation to treatment tracked across branches, with reminders and follow-up automated.' },
      { name: 'Real estate developers', desc: 'Portal, ad and WhatsApp leads routed to the right project and agent in minutes, with site-visit scheduling automated.' },
      { name: 'Education', desc: 'Admissions pipelines from enquiry to enrolment, timed to the academic calendar.' },
      { name: 'Jewellery and retail', desc: 'Scheme members, wedding enquiries and showroom visits tracked and followed up.' },
      { name: 'Professional services', desc: 'Long sales cycles kept warm with nurture that does not become noise.' },
      { name: 'B2B and exporters', desc: 'Pipeline across India and the Gulf tracked from a Kerala base.' },
    ],
    engagementsHeading: 'How we work together',
    engagements: [
      { name: 'Implementation project', desc: 'CRM, WhatsApp, routing and automation built and launched on a fixed scope.' },
      { name: 'Foundations inside a marketing retainer', desc: 'The CRM and automation layer built as the first phase of a growth engagement.' },
      { name: 'Ongoing optimisation', desc: 'Sequences, scoring and reporting improved monthly from the data.' },
    ],
    detail: [
      {
        heading: 'The CRM that fills itself',
        body: [
          'The reason CRMs die in Kerala is data entry. The salesperson closes on WhatsApp at nine at night and is expected to record it in a desktop system the next morning. By the second week nothing is recorded and the owner is back to asking around. When the WhatsApp Business API is integrated with the CRM, the conversation is the record: every message logged against the customer, every enquiry timestamped with its source, every quote sent from the CRM screen and attached to the deal, without the salesperson doing anything they were not already doing.',
          'The same integration lets the system answer first, within minutes, with a qualified templated reply in the language of the enquiry, so the customer is engaged before a person is awake.',
        ],
        points: [
          { name: 'Conversation is the record', desc: 'WhatsApp messages logged automatically against the customer.' },
          { name: 'Instant first reply', desc: 'Templated, qualified, in Malayalam or English, within minutes.' },
          { name: 'Quotes from the CRM', desc: 'Sent from the same screen and attached to the deal.' },
          { name: 'Nothing extra to do', desc: 'The salesperson works from the phone as before.' },
        ],
      },
      {
        heading: 'Right branch, right person, in seconds',
        body: [
          'A hospital group receives a lead from a Google ad, a Practo listing and a WhatsApp click, sometimes from the same patient, and it can reach three different branches or none. Routing rules decide instantly by department, branch, language and availability, deduplicate against the existing record, tag the lead with its source, and notify the coordinator on the channel they actually check. If nobody responds, the lead escalates rather than going cold.',
          'A developer routes by project and by whether the buyer is local or in the Gulf; a school by year group and campus; a jeweller by showroom; a B2B firm by territory and deal size.',
        ],
        points: [
          { name: 'Rules per business', desc: 'Branch, department, project, language, territory or availability.' },
          { name: 'Deduplicated', desc: 'One record per person however many channels they used.' },
          { name: 'Source attached', desc: 'Every lead tagged for attribution from the moment it arrives.' },
          { name: 'Escalation', desc: 'Unanswered leads reassigned before they are lost.' },
        ],
      },
      {
        heading: 'Long cycles kept warm, not spammed',
        body: [
          'A hospital enquiry may take weeks to become a consultation, a school enquiry a whole admissions season, a real estate enquiry from Dubai a year and a visit home. Sequences keep the relationship alive with the right message at the right moment, in the customer’s language, and stop when they should. The design is in the handoffs: automation handles the first minute and the reminders, and a person is notified the moment the lead asks a real question or is ready to book.',
          'Response time and conversion are measured at each stage so the balance between automation and people can be adjusted from data rather than opinion.',
        ],
        points: [
          { name: 'Sequences by stage', desc: 'The right message at the right moment, in the right language.' },
          { name: 'Handoff triggers', desc: 'A person notified when the conversation needs one.' },
          { name: 'Sequences that end', desc: 'No noise forever.' },
          { name: 'Stage metrics', desc: 'Response time and conversion, adjusted monthly.' },
        ],
      },
      {
        heading: 'Consent you can defend',
        body: [
          'The Digital Personal Data Protection Act makes marketing automation the place where a business is most likely to get into trouble: a broadcast to numbers that never opted in, a list imported from an old spreadsheet, health or student data used for marketing without a basis. We capture consent with every lead per channel, record the basis for every contact, honour opt-outs automatically across WhatsApp, email and SMS, apply additional controls to health and student data, and host in Indian regions.',
          'The pipeline the business builds is one it is allowed to use, and the records exist to prove it.',
        ],
        points: [
          { name: 'Consent per channel', desc: 'Recorded with every lead at capture.' },
          { name: 'Opt-outs honoured', desc: 'Applied automatically across every channel.' },
          { name: 'Sensitive data', desc: 'Health and student data handled with extra controls.' },
          { name: 'Indian hosting', desc: 'Data kept in Indian regions.' },
        ],
      },
    ],
    extraFaqs: [
      { question: 'Which CRM should a Kerala business use?', answer: 'Zoho fits most SMEs on cost and localisation, HubSpot fits marketing-led teams, Salesforce fits larger organisations, and WhatsApp-first teams sometimes need a lighter tool with the Business API integrated. We recommend after seeing how your team actually sells and we implement all of them.' },
      { question: 'Will our sales team have to stop using WhatsApp?', answer: 'No. The WhatsApp Business API is integrated so conversations are logged against the customer automatically, replies go out from the CRM screen and the salesperson keeps working from their phone.' },
      { question: 'How fast can a lead get a reply?', answer: 'Within minutes, day or night, with a qualified templated reply in the language of the enquiry, and a person notified when the conversation needs one. Response time is measured and reported.' },
      { question: 'Can leads be routed to the right branch?', answer: 'Yes. Rules by branch, department, project, language, territory or availability decide in seconds, with deduplication, source tagging and escalation if nobody responds.' },
      { question: 'Can you move us off spreadsheets or another CRM?', answer: 'Yes. Data is mapped, cleaned, migrated in rehearsed stages and reconciled, and the team is trained on the new process before the old one is switched off.' },
      { question: 'How do you handle consent under the DPDP Act?', answer: 'Consent is captured with every lead per channel, recorded, and honoured automatically across WhatsApp, email and SMS, with extra controls for health and student data and hosting in Indian regions.' },
      { question: 'Can the CRM send results back to Google and Meta?', answer: 'Yes. Qualified enquiries and closed sales are sent back as offline conversions so the platforms optimise for revenue rather than form fills.' },
      { question: 'How long does implementation take?', answer: 'Four to eight weeks for a CRM for a sales team, two to four for the WhatsApp Business API integration, depending on the process and the data to migrate.' },
      { question: 'Can you integrate property portal and Practo leads?', answer: 'Yes. Portal, listing and ad leads are captured with their source, deduplicated against existing records and routed by project, department or branch, and answered on WhatsApp within minutes.' },
      { question: 'Does the automation work in Malayalam?', answer: 'Yes. Sequences, templates and documents are written natively in Malayalam and English and sent in the language of the enquiry.' },
    ],
  },

  'seo-services': {
    overview: [
      'SEO for Kerala businesses, run from Kochi and judged on one number: the enquiries and revenue that organic search produces. Everything else, rankings, traffic, domain scores, is a leading indicator we report on the way there. A hospital that ranks first for a term nobody with a condition types, or a developer with traffic that never becomes a site visit, has not been served by SEO. It has been served a report.',
      'The Kerala search market has a specific shape. Malayalam and Manglish queries carry demand that almost nobody serves well. The first page for most commercial terms is held by Practo, Justdial, Sulekha, the property portals and national brands rather than by the local businesses doing the work. And most local business sites cannot be read by Google at all, because they were built on a framework that renders in the browser. The opportunity is in all three, in that order.',
      'So the programme runs in that order: fix what Google sees, build the Malayalam track that competitors have ignored, take the local and service terms back from the aggregators one at a time, and earn the authority from Kerala sources that a national brand cannot copy. Search Console, GA4 and the CRM are connected so every month’s report shows enquiries by page and query.',
      'Hospitals and clinics, developers, jewellery and retail chains, schools and colleges, resorts, professional firms and B2B companies selling from Kerala to India and abroad.',
    ],
    capabilitiesHeading: 'What the programme delivers',
    capabilities: [
      { name: 'Technical audit and remediation', desc: 'Crawlability, indexation, rendering, Core Web Vitals, structured data and architecture fixed in priority order and verified in Search Console.' },
      { name: 'Local SEO across Kerala', desc: 'Google Business Profile management, Indian citations, review workflows and district content for every real location.' },
      { name: 'Malayalam search track', desc: 'Malayalam and Manglish keyword research, native content and correct language markup, reported separately from English.' },
      { name: 'Content strategy and production', desc: 'Guides, service and product content planned from demand and structured so search engines and AI assistants can quote it.' },
      { name: 'E-commerce SEO', desc: 'Category architecture, product optimisation, facet control, schema and internal linking for Shopify, WooCommerce and custom stores.' },
      { name: 'Authority and digital PR', desc: 'Links and mentions earned through useful content, Kerala and Indian publisher outreach and partnerships. No bought links.' },
      { name: 'Diaspora and national reach', desc: 'Search coverage for NRI buyers and for Kerala brands selling across India, with content planned per audience.' },
      { name: 'Reporting on enquiries', desc: 'Search Console, GA4 and CRM connected so organic reporting shows enquiries and revenue by page and query.' },
    ],
    specsHeading: 'What to expect and when',
    specsColumns: ['Workstream', 'Typical timeline', 'Evidence it is working'],
    specs: [
      ['Technical remediation', 'Weeks 1 to 6', 'Indexed pages up, errors down in Search Console'],
      ['Local SEO and Business Profile', 'Weeks 4 to 12', 'Map pack visibility, calls and WhatsApp clicks'],
      ['Content programme', 'Month 2 onwards', 'Impressions and clicks on new pages'],
      ['Authority building', 'Month 3 onwards', 'Referring domains and page-level rankings'],
      ['Competitive city terms', 'Months 6 to 12', 'Page one positions and enquiries by query'],
    ],
    useCasesHeading: 'Who we run SEO for',
    useCases: [
      { name: 'Hospitals and clinics', desc: 'Treatment, condition and doctor content that ranks and stays within NMC advertising rules, for patients in Kerala and the Gulf.' },
      { name: 'Real estate', desc: 'Locality guides, project pages and buyer intent content that compete with the portals rather than depend on them.' },
      { name: 'Jewellery and retail', desc: 'Showroom, category and product SEO for chains across the districts.' },
      { name: 'Education', desc: 'Course, admission and campus content aligned to what parents and students search.' },
      { name: 'Tourism and hospitality', desc: 'Destination and property content that ranks alongside the OTAs and drives direct bookings.' },
      { name: 'B2B and SaaS', desc: 'Capability and comparison content for Infopark and Technopark companies selling beyond Kerala.' },
    ],
    engagementsHeading: 'How we engage',
    engagements: [
      { name: 'SEO retainer', desc: 'The full programme monthly, with the balance of technical, content and authority work adjusted as the data dictates.' },
      { name: 'Technical audit and fix', desc: 'A fixed-scope audit with remediation for sites where the foundation is the problem.' },
      { name: 'Content programme', desc: 'Bilingual content on a set cadence for businesses with the technical basics in place.' },
    ],
    detail: [
      {
        heading: 'Fix what Google sees before writing a word',
        body: [
          'The first audit of a Kerala business site usually finds the same list. Pages rendered in the browser that the crawler receives empty. Two or three URLs for every page thanks to a language switcher and tracking parameters. A homepage that takes six seconds to load on a mid-range phone because of a slider and a dozen scripts. Structured data copied from a template that describes some other company. A sitemap that lists pages that no longer exist. Each of these caps what any amount of content can achieve.',
          'We audit against what Google actually receives, fix in order of impact, verify every fix in Search Console, and hand precise tickets to your developers or make the changes ourselves through the technology team.',
        ],
        points: [
          { name: 'Rendering', desc: 'Prerendered HTML so the crawler and AI assistants get the whole page.' },
          { name: 'Duplicates', desc: 'Language and parameter URLs canonicalised or consolidated.' },
          { name: 'Speed on real phones', desc: 'Templates tuned on mid-range Android over Jio and Airtel.' },
          { name: 'Verified', desc: 'Every fix confirmed in Search Console, not assumed.' },
        ],
      },
      {
        heading: 'The Malayalam track nobody else runs',
        body: [
          'Search demand in Malayalam and Manglish is large across every consumer category in Kerala and the content serving it is thin, translated or absent. That is the widest open opportunity in the state’s search results. Translation does not close it: Malayalam readers recognise translated text and Google treats it as the weak content it is. The pages that win are researched from Malayalam queries, written natively in the register the district uses, marked up so Google serves the right version to the right searcher, and reported on their own so the business sees what the language produces.',
          'For many clients the Malayalam track is where the first organic enquiries arrive, months before the competitive English terms move.',
        ],
        points: [
          { name: 'Malayalam research', desc: 'Queries mapped with spelling and transliteration variants.' },
          { name: 'Native writing', desc: 'In the register of the audience, by native speakers.' },
          { name: 'Language markup', desc: 'Hreflang and canonicals so the right version ranks.' },
          { name: 'Separate reporting', desc: 'Enquiries by language, so the return is visible.' },
        ],
      },
      {
        heading: 'Taking terms back from the aggregators',
        body: [
          'Search for a dentist in Kakkanad, a flat in Kozhikode or a CBSE school in Trivandrum and the first page belongs to platforms that list local businesses and sell them the leads. They hold those positions with scale and years of authority, and no local business will outspend them. What a local business can do is be more specific: content written by the doctor, the developer or the principal about this practice, this project, this campus, a Google Business Profile that outperforms a listing, reviews that read as real, and the locality detail a platform page cannot have.',
          'We map which aggregator holds which term, pick the queries where a local page can realistically win, and work through them in order of value.',
        ],
        points: [
          { name: 'Term map', desc: 'Which platform holds which query, and where the gaps are.' },
          { name: 'First-hand pages', desc: 'Content only the business doing the work can write.' },
          { name: 'Business Profile', desc: 'Managed as a channel, per real branch, in both languages.' },
          { name: 'In order of value', desc: 'The queries that convert, displaced one at a time.' },
        ],
      },
      {
        heading: 'Authority a national brand cannot copy',
        body: [
          'Links and mentions from Kerala publishers, trade associations, chambers, colleges, hospitals’ professional bodies and event organisers tell Google exactly which state a business belongs to, and a competitor in Bengaluru or Mumbai cannot easily acquire them. We earn them through content worth citing, partnerships and digital PR, never through purchase, because bought links are the liability that surfaces at the next spam update.',
          'The monthly report shows referring domains and page-level rankings as leading indicators alongside the enquiries that are the point.',
        ],
        points: [
          { name: 'Kerala sources', desc: 'Publishers, associations, institutions and events in the state.' },
          { name: 'Content worth citing', desc: 'Guides and data local sources want to reference.' },
          { name: 'No purchased links', desc: 'Earned only, reported transparently.' },
          { name: 'Leading indicators', desc: 'Referring domains and rankings alongside enquiries.' },
        ],
      },
    ],
    extraFaqs: [
      { question: 'How long before SEO produces enquiries in Kerala?', answer: 'Technical fixes show in Search Console within weeks. Local and Malayalam terms usually produce enquiries within two to four months. Competitive city-wide English terms need six to twelve months of sustained work. Leading indicators are reported monthly so progress is visible before rankings move.' },
      { question: 'Why does our site not rank at all?', answer: 'Most often because Google receives an empty page from a browser-rendered framework, compounded by duplicate URLs and slow templates. Fixing what Google sees is the first workstream, and it often produces the first movement on its own.' },
      { question: 'Do you do Malayalam SEO?', answer: 'Yes, as a separate track: Malayalam and Manglish research, native writing, correct language markup and separate reporting. For many clients it is where the first organic enquiries come from.' },
      { question: 'Can we outrank Practo, Justdial or the property portals?', answer: 'For specific local and service terms, yes. Platforms win on scale, but a page written by the doctor, the developer or the principal, with a strong Business Profile and real reviews, wins the queries that actually convert. We map where that is realistic.' },
      { question: 'Do you guarantee rankings?', answer: 'No. Nobody controls Google. We commit to a sound technical foundation, content built from real demand, earned authority and honest monthly reporting on enquiries as well as rankings.' },
      { question: 'Do you buy links?', answer: 'No. Authority is earned from Kerala publishers, associations and institutions through content and outreach. Bought links are a liability.' },
      { question: 'Can you run SEO for our branches across Kerala?', answer: 'Yes. One Business Profile per real branch, district pages with genuine local content, schema per location and a structure that lets each rank without duplicating the others.' },
      { question: 'What does the monthly report contain?', answer: 'Organic enquiries and revenue by page, query and language from Search Console, GA4 and the CRM, plus rankings, indexation and authority as leading indicators, with a short weekly note on what changed.' },
    ],
  },

  'performance-marketing': {
    overview: [
      'Performance marketing and paid ads for Kerala businesses, run from Kochi as one measured system: Google, Meta, YouTube and LinkedIn, with spend judged on what it produced after the click, offline conversions sent back to the platforms, creative tested on a cadence in Malayalam and English, and budgets moved weekly to whatever is producing. The companion to our performance advertising service, with the emphasis on the measurement and the operating rhythm that make paid media pay.',
      'The reason performance marketing fails in Kerala is rarely the platforms. It is the absence of a system around them: no definition of a qualified enquiry, no tracking of WhatsApp and calls, no CRM that carries the source, no creative testing, no honest accounting for returns and cash-on-delivery failures, and a monthly report that shows clicks. The system is the product, and it is what this page describes.',
      'We build the system first, run the channels on it, and report from spend to revenue in the numbers the accountant uses. Diaspora campaigns into the Gulf are run with a working view of that audience from our UAE office, and district-level campaigns are structured because Kerala is fourteen markets, not one.',
      'We run performance marketing for hospitals and clinics, real estate developers, jewellery and retail chains, education, hospitality, e-commerce and B2B companies across the state.',
    ],
    capabilitiesHeading: 'The operating system behind the ads',
    capabilities: [
      { name: 'Qualified enquiry definition', desc: 'Agreed in writing in the first workshop, applied in the CRM, and used to judge every campaign.' },
      { name: 'Full-funnel tracking', desc: 'Forms, calls, WhatsApp and walk-ins tracked with source and campaign, into the CRM and back to the platforms.' },
      { name: 'Weekly budget reallocation', desc: 'Spend moved to what is producing every week, in writing, with the reasoning.' },
      { name: 'District and language structure', desc: 'Campaigns segmented by district and by Malayalam and English so each is bid and reported on its own economics.' },
      { name: 'Creative testing cadence', desc: 'New hooks and formats every few weeks from Infynix Media, with losers cut early.' },
      { name: 'Landing page testing', desc: 'Structured tests on headlines, forms, proof and offers, with winners applied to the organic pages too.' },
      { name: 'Contribution accounting', desc: 'Returns, COD failures, fees and discounts counted so the result reflects what the business kept.' },
      { name: 'Seasonal planning', desc: 'Onam, Vishu, wedding season, admissions and the monsoon planned into budgets in advance.' },
    ],
    specsHeading: 'Channels, timelines and what we measure',
    specsColumns: ['Channel', 'Time to first signal', 'Primary measure'],
    specs: [
      ['Google Search', '1 to 2 weeks', 'Cost per qualified enquiry'],
      ['Performance Max and Shopping', '3 to 4 weeks', 'Contribution after returns, new customer rate'],
      ['Meta and Instagram', '2 to 3 weeks', 'Cost per lead or order, quality from CRM'],
      ['YouTube', '3 to 4 weeks', 'View-through enquiries, brand search lift'],
      ['LinkedIn (B2B)', '4 to 6 weeks', 'Meetings booked, pipeline created'],
      ['Diaspora campaigns', '3 to 4 weeks', 'Cost per WhatsApp conversation by country'],
    ],
    useCasesHeading: 'Who this is built for',
    useCases: [
      { name: 'Lead-driven businesses', desc: 'Hospitals, real estate, education and financial services where enquiry quality matters more than volume.' },
      { name: 'Multi-branch retail', desc: 'Jewellery, textile and electronics chains that need results by branch, not a state total.' },
      { name: 'E-commerce and D2C', desc: 'Kerala brands selling across India with COD returns and fees counted in the numbers.' },
      { name: 'Hospitality', desc: 'Resorts and restaurants measuring direct bookings against OTA commission.' },
      { name: 'B2B and SaaS', desc: 'Infopark and Technopark companies selling nationally and abroad, measured on pipeline.' },
      { name: 'Diaspora sellers', desc: 'Businesses whose buyers include NRI families in the Gulf.' },
    ],
    engagementsHeading: 'How we work together',
    engagements: [
      { name: 'Performance retainer', desc: 'Channels, creative, testing and reporting monthly, with budgets moved to what is producing.' },
      { name: 'Foundations project', desc: 'Tracking, consent, CRM and landing pages built before spend begins.' },
      { name: 'Audit and rescue', desc: 'A paid audit of accounts spending without producing, with a written plan.' },
    ],
    detail: [
      {
        heading: 'The first ninety days',
        body: [
          'The first month is foundations: access, tracking, CRM fields, the enquiry definition, consent to the DPDP Act and the first landing pages, with a small amount of search spend to start collecting data. The second month is the first real campaigns across the channels that fit, with creative testing under way and the weekly notes showing what is moving. The third month is the first honest review: what produced qualified enquiries at what cost, what to cut, where to move the budget.',
          'By day ninety you have a measured system, three months of real numbers and a plan for the next quarter built on them rather than on a proposal. That is the point at which most clients decide to scale, and the point at which the ones who should not are told so.',
        ],
        points: [
          { name: 'Month one', desc: 'Foundations, tracking, enquiry definition, first pages and a data-gathering budget.' },
          { name: 'Month two', desc: 'Campaigns live across the fitting channels, creative testing under way.' },
          { name: 'Month three', desc: 'The first quarterly review on real numbers, with cuts and reallocations.' },
          { name: 'Quarter two onwards', desc: 'Scaling what works, with SEO starting to carry weight.' },
        ],
      },
      {
        heading: 'Kerala economics: margins, COD and the calendar',
        body: [
          'Kerala businesses run tighter margins than most agency models assume, cash on delivery produces return rates that the ROAS number hides, and the year has an Onam-shaped peak that flat budgets miss. A campaign that looks profitable on the platform dashboard can be losing money once returns, margin and seasonality are counted.',
          'We set targets from your real margin and close rate, count COD returns against results, and plan budgets around the Kerala calendar so the peak is funded and the trough is not overspent.',
        ],
        points: [
          { name: 'Margin-aware targets', desc: 'Cost per acquisition set from what you actually earn.' },
          { name: 'COD accounting', desc: 'Returns counted against results, not ignored.' },
          { name: 'Seasonal budgets', desc: 'Onam, Vishu, wedding season and the monsoon planned in advance.' },
          { name: 'Honest minimums', desc: 'The spend needed for a readable result, stated before you commit.' },
        ],
      },
      {
        heading: 'Scaling a Kerala brand beyond the state',
        body: [
          'Many Kerala brands, in food, Ayurveda, apparel and consumer goods, reach a point where the state is saturated and the next growth is national or in the Gulf. Performance marketing is how that expansion is tested cheaply: campaigns in Bengaluru, Chennai, Mumbai and the Malayali pockets of every metro, or into the UAE, Saudi Arabia and Qatar, measured on cost per order after returns, before a distributor or a warehouse is committed.',
          'We run those tests with the same measurement discipline as the home market, report by city or country, and say honestly which markets are ready and which are not.',
        ],
        points: [
          { name: 'City-by-city tests', desc: 'Small, measured campaigns before committing distribution.' },
          { name: 'Malayali pockets first', desc: 'Diaspora audiences in every metro and the Gulf targeted first.' },
          { name: 'Returns counted', desc: 'Cost per order after COD returns, by city or country.' },
          { name: 'Honest readout', desc: 'Which markets are ready, in writing.' },
        ],
      },
      {
        heading: 'Questions to ask any agency before you sign',
        body: [
          'A few questions separate the teams that will produce revenue from those that will produce reports. Ask who owns the ad accounts and the analytics property, and what happens if you leave. Ask how a qualified enquiry is defined and where that definition lives. Ask to see a real weekly update sent to another client, numbers redacted. Ask what they would stop doing in month three if it was not working. Ask how Malayalam creative is produced, how WhatsApp enquiries are tracked, and whether they have run campaigns in your category under its advertising rules.',
          'Any agency that hesitates has not built a measured system for a Kerala business before. We are happy to answer every one of these on the first call.',
        ],
        points: [
          { name: 'Account ownership', desc: 'Everything in your name from day one, with admin access documented.' },
          { name: 'Enquiry definition', desc: 'Agreed in the first workshop and applied in the CRM, not in a slide.' },
          { name: 'Proof of process', desc: 'Real weekly notes and a live dashboard, shown before you sign.' },
          { name: 'Exit terms', desc: 'A notice period in weeks and a clean handover of every asset.' },
        ],
      },
    ],
    extraFaqs: [
      { question: 'How is this different from your performance advertising service?', answer: 'Performance advertising covers the channels and the creative. Performance marketing is the system around them: the enquiry definition, the tracking, the CRM, the weekly reallocation, the contribution accounting and the operating rhythm. Most clients take both as one engagement; the pages exist so each is explained properly.' },
      { question: 'How much should we spend to get a readable result?', answer: 'It depends on your category and cost per click. We state the minimum before you commit, and we will say if the budget is too small to produce a signal rather than take it and report clicks.' },
      { question: 'Do you handle cash on delivery returns in the reporting?', answer: 'Yes. COD returns are counted against results so the return on ad spend reflects what the business actually kept, not what the platform dashboard shows.' },
      { question: 'Can you help a Kerala brand expand to other cities or the Gulf?', answer: 'Yes. We test new markets with small, measured campaigns city by city or country by country, starting with Malayali audiences, and report cost per order after returns so the decision to commit distribution is made on numbers.' },
      { question: 'Do you guarantee a cost per lead?', answer: 'No. We set a target from your margin and close rate in the first workshop and report against it from month one, and we tell you honestly when it is not being met and why.' },
      { question: 'Who owns the ad accounts?', answer: 'You do, from day one, with admin access documented. If we part ways, everything stays with you.' },
      { question: 'Can you work alongside our in-house team?', answer: 'Yes. We take one or more channels, or the measurement layer, and report into your existing tools.' },
      { question: 'How do you report?', answer: 'A short written note every week on what changed and what it did, a monthly review with spend, enquiries, qualified enquiries and revenue by channel and district, and a live dashboard, in the definitions your accountant uses.' },
      { question: 'Do you manage product feeds for Shopping?', answer: 'Yes. Feed optimisation, custom labels by margin and role, availability sync and supplemental data are part of every Shopping and social commerce engagement.' },
    ],
  },
};
