// Imagery for the location landing pages.
//
// All five files are WebP generated by scripts/optimise-images.js from sources
// that ranged from 425 KB to 1.9 MB. Each is served at the width it is actually
// displayed, with a 2x for retina.

import marketing from '../assets/lp/lp-marketing.webp';
import marketing2x from '../assets/lp/lp-marketing@2x.webp';
import media from '../assets/lp/lp-media.webp';
import media2x from '../assets/lp/lp-media@2x.webp';
import technology from '../assets/lp/lp-technology.webp';
import technology2x from '../assets/lp/lp-technology@2x.webp';
import regions from '../assets/lp/lp-regions.webp';
import regions2x from '../assets/lp/lp-regions@2x.webp';
import kochi from '../assets/lp/lp-kochi.webp';
import kochi2x from '../assets/lp/lp-kochi@2x.webp';

const IMAGES = {
  marketing: {
    src: marketing,
    srcSet: `${marketing} 640w, ${marketing2x} 1120w`,
    alt: 'Infynix marketing dashboards and campaign reporting on a desk setup',
  },
  media: {
    src: media,
    srcSet: `${media} 640w, ${media2x} 1120w`,
    alt: 'Content production desk with camera, ring light and video editing timeline',
  },
  technology: {
    src: technology,
    srcSet: `${technology} 640w, ${technology2x} 1120w`,
    alt: 'Connected devices and systems visualised as a single linked platform',
  },
  regions: {
    src: regions,
    srcSet: `${regions} 640w, ${regions2x} 1120w`,
    alt: 'Laptop showing a map of the regions Infynix Solutions delivers into',
  },
  // Deliberately captioned as the city rather than as our building: the Infynix
  // office is in the National Pearl Star Building, Edappally, and this is a
  // general Kochi photograph. Presenting it as our premises would be a lie in
  // the alt text and in the picture.
  kochi: {
    src: kochi,
    srcSet: `${kochi} 640w, ${kochi2x} 1120w`,
    alt: 'Kochi, Kerala, where the Infynix engineering team is based',
  },
};

/** Lead image for the page hero, chosen from what the page is actually about. */
export const heroImageFor = (page) => {
  if (/social|media/i.test(page.service)) return IMAGES.media;
  return page.category === 'technology' ? IMAGES.technology : IMAGES.marketing;
};

/** Supporting image for the "why this place" section. */
export const localImageFor = (page) =>
  page.city === 'Kochi' ? IMAGES.kochi : IMAGES.regions;

export default IMAGES;
